FROM python:3.10-slim

WORKDIR /app

# Copia o arquivo de dependências
COPY requirements.txt .

# Instala as dependências do Python
RUN pip install -r requirements.txt

# Copia o restante do código
COPY . .


EXPOSE 5003

# Executa a aplicação
CMD ["python", "app/app.py"]
