version: '3.9'

services:
  mysql_db:
    image: mysql:5.7  # Usa a imagem do MySQL 5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # Senha do root
      MYSQL_DATABASE: SkyTech
    ports:
      - "3309:3306"                  # host:container
    volumes:
      - db_data:/var/lib/mysql       # Persistência dos dados

  
  manutencao:
    build:
      context: ./manutencao
    ports:
      - "5001:5001"

  aeronaves:
    build:
      context: ./aeronaves
    ports:
      - "5002:5002"
    

  

volumes:
  db_data:
